old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            lazy: true
            keepalive: false

    producers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }

    multiple_consumers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }
            queues:
                elastic_events:
                    name: elastic_events
                    routing_keys:
                        - 'App.Domain.#'
                    callback: App\Infrastructure\Share\Event\Consumer\SendEventsToElasticConsumer
