old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            keepalive: false

    producers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }


    multiple_consumers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }
            queues:
                aync_event_handlers:
                    name: aync_event_handlers
                    routing_keys:
                        - 'App.Domain.#'
                    callback: App\Infrastructure\Share\Event\Consumer\EventQueueConsumer
                elastic_events:
                    name: elastic_events
                    routing_keys:
                        - 'App.Domain.#'
                    callback: App\Infrastructure\Share\Event\Consumer\SendEventsToElasticConsumer