security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12
    providers:
        users:
            id: 'App\Infrastructure\User\Auth\AuthProvider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: true
            
        api_auth:
            pattern:  ^/api/auth
            stateless: true
            anonymous: true

        api_signup:
            pattern:  ^/api/signup
            stateless: true
            anonymous: true

        api_secured:
            pattern:  ^/api
            provider: users
            stateless: true
            guard:
              authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

        secured_area:
            provider: users
            anonymous: ~
            guard:
              entry_point: 'App\Infrastructure\User\Auth\Guard\LoginAuthenticator'
              authenticators:
                - 'App\Infrastructure\User\Auth\Guard\LoginAuthenticator'
            form_login:
              login_path: /sign-in
              check_path: sign-in
            logout:
              path: /logout
              target: /

    access_control:
        - { path: ^/profile/*,  roles: ROLE_USER                    }
        - { path: ^/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/,       roles: IS_AUTHENTICATED_FULLY       }
