version: '3'

services:

  nginx:
    image: nginx:1.11-alpine
    ports:
      - "80:80"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    build:
      dockerfile: etc/dev/php/Dockerfile
      context: .
    image: jorge07/cqrs:builder
    ports:
      - "2323:22"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rmq

  workers:
    image: jorge07/cqrs:builder
    volumes:
      - .:/app
    command: ['/app/bin/console', 'messenger:consume-messages', 'amqp']

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
    volumes:
      - db_data:/var/lib/mysql

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601
    volumes:
      - "$PWD/etc/dev/kibana/config:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - "9200:9200"

volumes:
  db_data:
