version: '3'

services:

  nginx:
    image: nginx:1.11-alpine
    ports:
      - "80:80"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    image: jorge07/alpine-php:7.1-dev-sf
    ports:
      - "2323:22"
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
