version: '3'

services:

  nginx:
    image: nginx:1.11-alpine
    ports:
      - "80:80"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    image: jorge07/alpine-php:7.2-dev-sf
    ports:
      - "2323:22"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rmq

  workers:
    image: jorge07/alpine-php:7.2-dev-sf
    volumes:
      - .:/app
    command: ['/app/bin/console', 'rabbitmq:multiple-consumer', 'events']

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
    volumes:
      - db_data:/var/lib/mysql

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - 5601:5601
    volumes:
      - "$PWD/etc/dev/kibana/config:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

volumes:
  db_data:
