replicaCount: 1

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 80

image:
  php:
    repository: jorge07/cqrs
    tag: latest
  nginx:
    repository: jorge07/cqrs
    tag: nginx-latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  hosts:
    - demo.minikube.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

elasticsearch:
  selfHosted: true
  replicas: 1
  antiAffinity: "soft"
  esJavaOpts: "-Xmx128m -Xms128m"
  resources:
    limits:
      memory: 1G
    requests:
      cpu: 250m
      memory: 512Mi

rabbitmq:
  selfHosted: true
  rbacEnabled: true
  rabbitmq:
    username: guest
    password: guest
    erlangCookie: "SWQOKODSQALRPCLNMEQG"

mysql:
  selfHosted: true
  mysqlRootPassword: api
  mysqlUser: api
  mysqlDatabase: api
  imageTag: 8.0.16
  args:
  - --default-authentication-plugin=mysql_native_password

traefik:
  enabled: true
  rbac:
    enabled: true
  dashboard:
    enabled: true
    domain: traefik.local.minikube.com
  serviceType: NodePort

parameters:
  app:
    env: prod
    secret: thisisnotasecret
  mysql:
    host: cqrs-mysql
    port: 3306
    database: api
    user: root
    pass: api
  rabbit:
    host: "amqp://guest:guest@cqrs-rabbitmq:5672"
  elastic:
    host: "elasticsearch-master:9200"
  jwt:
    hostPath: "/app/config/packages/jwt"
    secretKey: |
      -----BEGIN RSA PRIVATE KEY-----
      Proc-Type: 4,ENCRYPTED
      DEK-Info: AES-256-CBC,792228813A9EC4CE7F0C2FA88B8F7E4A

      c45CpYXNxDnAQV3BBYy8te6oDL/dwVHmU1Ckkc3cXNG34n/wbD7Hj1E7u6SjZKdO
      I2mAuqWvSqPIFb0/x1f1Ft21W8JZlD3zj7dd/kN52xBl1XYhO1GMVGO8jKip6TpY
      RLzN5TGn4aSzZcp1g2tLxurc/J96JjIYGx2b1OA6drc6F5AHx2lTluFnnXC8dyEj
      HQE3xfHC42ILluIPU/3CVgRzTz23G2xsn/iz5P2jHfj6bvLseJsTTgge57Wbsa
      qprszljEwwlULQtt3EU2M8Kcydh9PE3uwwwuejpXg5nflrOer6y9joY84LeLdYq
      1BFfY3PEII2ZgcsUx1wPrd5Ojw0iPS3BSHedaEGJiGAEiQl0NbU/VxOtQmigwhw
      TrmqlXDJT08LBKfeTneDpfZZIkwFrSW9GguZczMx5bGRHThEXkalwhZqsfwzuOhl
      TqMtbJ5MdI263piHwOjuIsA6/qa5Vy0cRJjURSyjc3y0Qku1XVRjJMh6FAfwyZtM
      0KaX/ghUBDA4mCWe5MDhld2plSaTPqZAK1lyMfAVgdFNaxhIRhjOKcojY6OFTjN
      bcdvh2VObC8bs5VtilIRCqEnvk5b7tz3xTyT6p1n0pux0hHGElrNX0JJjumrpa5
      f0nbLllpRxf2Kz357EGn17bdPmj7Kh9FAqLsunV3LObt4nW/j4mXLdtAb7BgP
      zgQuf/5/0Kbvx1lycuhBpP6auRLbmP0cmhZ03acRpnZGtQjRXbxsMDGWxK/eQw2
      MeFKLDBqtMOjc8y5EAqHyavAfp3YwzbWMAAfxz6bZOwvy30tsBpL83iBHQ7wGq7
      b/BKdOcc6i3tz7nfDK7GVODBcpuq9ptTqJmeTV3gPAVaqnSIHq3jb0jVdnnURukx
      9sE/IBRqo690hVWj5TYr1ZxzhEaU7ip8G6qbftI59y3yPnK7QmkcyMfXhtfLTer
      BZRyXMdruCyltzFFScKOKP6x7qsuQ60kpWvCVWglL8mit4XI9bHUiZ2wwwhlGuP
      nNLkU7IVtY7L/NcMAa2aNMM9ezr19QoLbjoH91gxI3fsm4u8UpBZ7kRUnucOmj
      Hh17lG9Xbl/1kqshHSFDRdBVuFZKmRPtIJpi5V3sVJKvoqjbcfeoXjC97IaSZJYU
      xFzZWL3xD/vn5JljhlsswTRKpZTyhgGrPKRzTvCZcbThrkweE6D3fBVVim6ltLI
      uhNWAn/ZlZv1F4K7nEtgqBwJWsB7Xs33J0DOWjiU20/oCg9dQQkyiQ5zGJA2tki
      3D/GdvabB035ZeJ8x345DRCDuMeAjTu4fkfbiFLUd8YGgXfUNk3riPCSxUuOuUf
      UQtnQiq7Tg2UTxieunv/ni03W3muSuPdNJ0z2okvMeMeZuDmTr0TlTWhri77eN
      pTcqb/1V1Nje8kKTmLTVnDimdfJDtr6c11BMIwOOVnhKF2POh4bQChJSYY5yx5LQ
      5gL0qbKhOA5McvDMLVASI/wilhF3Ji2StUuinjSncyVJSxkOA56tG/ASMTYbynws
      vg9s0IfuD0g3FxG54KQw6QrYMEuMy3CU2tG/UHO46V6YWHmQMvp/wvfkzq7b4n9
      o9o49uWdpnlml5T5dY9FUdJ9E0KE2nDGjqKSk3gKAXFyeQGUmCjeb64u9gjz7Q1a
      2Gefzz8f0J13SfHNOgMMzvR6hja45JA0huaHT4qi3VqUbsvtuiAEJsGB1u6a2CH
      3HCgMB8A9H0EixZXh51PPVfZ6fksZSEz/2SEFCu02UXK3y8u/VcOWZ3qdOMFzaED
      N79SOBzNjNuV2/hGwOWFQFEHnYq9Dp2Q8voUEzLHBer5KG20U4NVQwalWv9KiBRB
      IJxBKURUltbd0ajgqx45uKVFxdmjNplwDTseygqFmYiFcyi4MaxPG58nYEz6rRB
      YiI68IWS3abre1ftWE5e6Mmod0XegBUk4dG4LSnsopdsYUUWvUi3uyKwnA5RSS
      Hnfghf9aGKNKpkiooTdQnya9NR7ZbqquQhW6sCn1IeochfMihOez7WQTbTNUtbL
      HP/hSjzCroBPavSnwlwefZSMHtZdF33UVr6hKddbHUDHtulQjaSzP6BFvyw/AHvq
      YAkxZcwJsjDxicp5G7ayYQE7t6geAs1iKrYO9Cl7Qe1LgstPfz4AbjmCLhd4Xjt
      GILyQP0c/ZX0vJBGZfm8n3Mfr2M9mdmEcNrODifuUdDHBRiq/uNyBgHcJBv1pR
      AsNH/CmAHROFVi4TtTVUlQszn1hfOWb7NPPLKo4ZpF1LBzr6f2Xohz8XWygV7pY
      WqrIkhvww/f7EiiI1bX62DsTkRNAZyHbZ7QEz5Cc4ZxNM5oDgW0QfIwfwlX84Q3m
      UUlkiV7802k8vXGdQIuo41vVxr4DUAlyQwd7UHtAuO1I87ByTEGUswX7ZSAxx8a
      z8msiKE1e/iav2Z/lrLanIUpCdqPYrnOMCNFyrzb1qsjH/ieLHyN3h93JmqEDPC
      90ND2JJdeuQkjBcvmcyo8gag/1UU4iatqEMRmdpfZf/kzHimIDIFgC0G3ZkRE0
      b/IpI1SYcClC2ab4CTfOJ7/tpMM9FZEEPvJFN/e4w9RrXJwerdbyxBn6thXVQ22
      Cl8aP0w/mr6IObSdVbkUdkeBynPsw7Em7NPrG7SzK79xd2EcgFJ8eQXFJVnE5MVe
      6yPrR9C4syif8GvfWrSNLHaNCOxPkz592ZN5wiXRt8YEwI8n8irDIHldDPNuGu
      f/nuwkRCwL2LQCZKHJO3sWBaoFc3N4vSTnWt89QpRPjCrOEf1xBbNJ5ZpfURw087
      5Kvs5BPJTOiWQK9FsVyseIU85mONNpxGPrGhnH/YYkXm88OawlNp87BGLO/KUdDx
      FKfLxNHNQIAxWI1lHkxC6pgCpgubuv779eO2L4AFuNndKXSmH/jb5HevfMPFjVEB
      HbBTF960aC1bNqP8lEVpIvPUcKfjjaMaVU1ZhFLVUWnl0fru41cI26rw/awGR0
      FPm2Joesld5OocUoPGhlQh5PPwE6ZdGCc4kuKO2KkYTTuLjkD8N6Irboeqccjx
      G2FcaxDlNATrv2H3mDhf7TjklpEnlMSXlGyUDoRoUFclLzYNNqiHoRmw9zvPumq3
      -----END RSA PRIVATE KEY-----
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArBmtoOEVG2GQ9ttdVxhc
      ZbLPrUADHQv1xVqV5H61mVcgfbtoRGdFUFuHD4DVopuSR2FhXMDRz0ukOTgwODOd
      ri6aG23Dir1oS4VS63OmvCEylS9EbgJkAJMGRM1/pDg61l89Xc7Wab2/Io3
      Q0o39obFVPLnvOSAKng7Ekm3fC8bRH3EvN2eYaFmvcxn97gEtym8x8PXYIICw
      WGRp0Tt62ldNhoWkWiY7c1c4M3A9gIasoNYyxSU7v2ozeMIStWtkDnzhVtYwDf
      3IOVvGxEBAzqYQ9ICI2eUQjf8edcbTIpkI4wBJ1Iz1wi9WJDc5OP/RMrcKPyO2p
      WeHuGbhasevkBeJi1fGClhjb/FwswGeEpcIVN59dafsPJ6U2Oj/RQJQQydEgnNfl
      rxCd/yIl3/Mo0gORL7j2WBPND5k/kVeEFAAA5S6KvwDfvVCJ7ka8IuAsZd5QZCC
      OzhpRjCT4JgBa9lJS/ShGguE3/0A0JnqpaqbBu3qMzRktnVqjTW0htjnmsCB8UH
      JTqqSKRUAygJ9MbxQo252xEgS0VHLDHA79ONiOVRZczbVtVjvZLLIVmeJYXTSc
      dq97Dy43xmYSsRL74Xgvf4LGoEgBEVDBg1ELonDoFwdVJwVqUgRk7awf8ZT
      gZV/5L0JJAEb4srJ9VrDntkCAwEAAQ==
      -----END PUBLIC KEY-----
    passphrase: development
    ttl: 3600
